### ISSUE TITLE
Supported fabric version

### ISSUE THREAD

**Issue by BakinDP** [luavixen/damagenumbers#1]
fabric.mod.json defines 1.20.4 as supported, but should be >=1.19 according to modrinth

Doesn't boot on 1.20.1 due to incompatibility with this minecraft version.

**Comment by BakinDP** [comment]
This should fix, the mod boots and works as intended!
[fabric.mod.json](https://github.com/luavixen/damagenumbers/files/14249341/fabric.mod.json)

**Comment by luavixen** [comment]
Sorry for the delay, I've been meaning to fix this issue and restructure the project to use Architectury. I have now completed these changes, and you can download the v1.1.0 version of the mod from Modrinth.
