### ISSUE TITLE
cant use for 1.20.1 

### ISSUE THREAD

**Issue by Gimgajim** [luavixen/damagenumbers#3]
gives me this errror:
Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
<html>Replace mod 'Damage Numbers' (damagenumbers) 1.0.0-fabric and mod 'Damage Numbers' (damagenumbers) 1.0.0-fabric with mod<br>'Damage Numbers' (damagenumbers), any version.</html>
More details:
<html>Mod 'Damage Numbers' (damagenumbers) 1.0.0-fabric requires any version between 1.20.4 (inclusive) and 1.21- (exclusive)<br>of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!</html>

**Comment by RashidFTW** [comment]
@Gimgajim Check the workaround I posted [here](https://github.com/luavixen/damagenumbers/issues/4#issuecomment-1956412923).

**Comment by Gimgajim** [comment]
> @Gimgajim Check the workaround I posted [here](https://github.com/luavixen/damagenumbers/issues/4#issuecomment-1956412923).
@RashidFTW i did the workaround and it lauched but in game the mod neither shows up in the mod menu thingy nor does the mod work :(

**Comment by luavixen** [comment]
I have fixed this issue, among others, in the v1.1.0 version of the mod, which can be downloaded from Modrinth.
