### ISSUE TITLE
Remove Requirement Of Library?

### ISSUE THREAD

**Issue by ExiledLizard** [luavixen/damagenumbers#6]
Hey, @luavixen, since I don't really like to install libraries, could you upload a version of your mod (as an external link, in this issue), for FABRIC: "Damage Numbers", that doesn't have a config screen, therefore, the damage colors are set to default (by you)? Or this requires a big rewrite, so no?

**Comment by luavixen** [comment]
I have made [a new commit](https://github.com/luavixen/damagenumbers/commit/e6c3e1913a5cd136995d4e4f489df8d448535733) that removes the hard dependency on YACL. Attempting to open the config screen without YACL will result in this message being displayed to the user:
![Screenshot](https://github.com/luavixen/damagenumbers/assets/7506308/afc60524-21cf-4341-8a18-d9b2daa65c1a)

I will release version 1.2.0 of Damage Numbers with this change soon, but it may take some time for the new update to be approved. In the meantime, you can download the update below.
Fabric: https://dl.vixen.link/h3n99k/damagenumbers-1.2.0-fabric.jar
Forge: https://dl.vixen.link/c3dhwy/damagenumbers-1.2.0-forge.jar

Does this work for you? I've had a few suggestions that YACL is a nuisance.

**Comment by ExiledLizard** [comment]
Thanks for responding! When I come back from school to my house, I'll
download & drag the (updated) mod in the mods folder, so I'll see if it works then.

**Comment by ExiledLizard** [comment]
@luavixen, I just ran the mod, and it was installed properly, but when I hit an entity, the mod crashed my client :( - here's the crash report, so that you could fix the mod: 
[crash-2024-04-17_17.07.30-client.txt](https://github.com/luavixen/damagenumbers/files/15018271/crash-2024-04-17_17.07.30-client.txt)
