### ISSUE TITLE
Limit range damage numbers appear

### ISSUE THREAD

**Issue by NolanHewitt** [luavixen/damagenumbers#7]
Damage numbers seem to appear no matter how far away the player is. For performance reasons, mainly with big mob farms, having the damage numbers only appear when within a certain range of a player would be nice.

**Comment by luavixen** [comment]
This is a really good idea! I'm sure I can find a way to limit the number of text particles the mod creates to prevent lag. I'll look into this very soon and release an update that prevents lag. I didn't really imagine this being an issue until you brought it up.

Could you possibly provide a world download that produces enough damage number particles to cause lag? Totally fine if not, but it would help me test whatever fix I create.

**Comment by NolanHewitt** [comment]
After doing some more testing with and without this mod I think the issue was the farm itself lagging the internal server in my single player world somehow. Though a limit to the number/range of text/particles would probably still be a good performance optimization but this mod alone probably isn't doing much to cause lag outside of some really extreme scenarios.

**Comment by luavixen** [comment]
Just wanted to let you know that while it hasn't yet been released in a new version, I did implement this functionality (https://github.com/luavixen/damagenumbers/commit/4294412a13efd9569c963ca6379435ea06463780) and it will be available in the upcoming releases coming out sometime soon. Thank you for your report!
